### ISSUE TITLE
Support for Flutter 3.0

### ISSUE THREAD

**Issue by ebelevics** [heremaps/here-sdk-ref-app-flutter#59]
When will new release for Flutter 3.0, most of the packages are already migrated, but this one remains outdated for quite of time.

**Comment by MaKra** [comment]
When https://github.com/flutter/flutter/issues/103630 hits Flutter production releases, we will start supporting it. Hopefully Flutter will release this soonish. This issue is sadly blocking a LOT of plugins, not just the HERE SDK.

**Comment by ebelevics** [comment]
Yes, I noticed. After making some changes in package and lauching the app, after back button HereMap widget shrinks in really odd way. Ok, thank you for quick response.

**Comment by crovax124** [comment]
this issue seems to be fixed in the flutter 3.3.0 beta.

**Comment by ebelevics** [comment]
Alright, it seems that Flutter is on 3.3 version officially. Any near future plans?

**Comment by stefan-troyke** [comment]
Yes, currently we started testing the latest Flutter version if it fixes all the issues.

**Comment by ebelevics** [comment]
Any updates?

**Comment by stefan-troyke** [comment]
Hi,

we plan the next release for the upcoming weeks. Sorry for the delay.

**Comment by stefan-troyke** [comment]
Hi,

I hope in the next sprint we can start on a new release

**Comment by crovax124** [comment]
What didn’t i get ? Isnt this solved with the 4.12.7.0 here sdk flutter ?

**Comment by ebelevics** [comment]
Thank you for pointing this out. Noticed on 4.12.8.0: This release of the HERE SDK requires Flutter 3.3.2. and Dart 2.18.

**Comment by stefan-troyke** [comment]
Hi,

yes, we support Flutter 3.3.2 since 4.12.7.0 but unfortuantely the blocking Flutter issue remain.

* https://github.com/flutter/flutter/issues/112929
* https://github.com/flutter/flutter/issues/89558
* https://github.com/flutter/flutter/issues/113051
* https://github.com/flutter/flutter/issues/112917

We can update the ref app but it will not solve not all issues with Android 12.

**Comment by stefan-troyke** [comment]
Hi, the support of the HERE SDK 4.12.10 and Flutter 3.3.2 was merged into the master today.
